apiVersion: apps/v1

kind: Deployment

metadata:

  name: nginx-deployment

  labels:

    app: nginx

spec:

  replicas: 2

  selector:

    matchLabels:

      app: nginx

  template:

    metadata:

      labels:

        app: nginx

    spec:

      containers:

      - name: nginx

        image: 292154417658.dkr.ecr.ap-south-1.amazonaws.com/demo2:SAMPLE-PROJECT-cnumber  

        ports:

        - containerPort: 80
